"""empty message

Revision ID: 992cdfa1d0fb
Revises: 
Create Date: 2023-01-31 07:22:18.149267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992cdfa1d0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=64), nullable=False, comment='用户名称(primary_key)'),
    sa.Column('info', sa.String(length=255), nullable=True, comment='用户信息'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('object',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False, comment='物品的全局唯一ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='物品名称'),
    sa.Column('count', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='物品数量'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='物品信息'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='物品归属的用户ID'),
    sa.ForeignKeyConstraint(['user_id'], ['user.name'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    op.drop_table('user')
    # ### end Alembic commands ###
