"""empty message

Revision ID: bf145247003e
Revises: 992cdfa1d0fb
Create Date: 2023-01-31 07:23:22.521017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf145247003e'
down_revision = '992cdfa1d0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=64), nullable=False, comment='物品归属的用户ID'))
        batch_op.drop_constraint('object_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_name'], ['name'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='物品归属的用户ID'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('object_ibfk_1', 'user', ['user_id'], ['name'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
